### ISSUE TITLE
Super great plugin, but it doesnt work on mobile(android)

### ISSUE THREAD

**Issue by so1975** [ydeltastar/godot-scene-texture#1]
Awesome plugin! Works on Pc, but doesnt on android? Textures are just white. Tried all the settings, but the result is the same.

**Comment by ydeltastar** [comment]
The demo project? What node or material are you using the texture? What is Godot's version and rendering method you are using? What nodes are in the scene to be rendered? Are there any errors or warnings?

**Comment by so1975** [comment]
Godot 4.3 stable. Mobile renderer. Just made fresh project with only control node with texture rect with scene material. Scene material is loading Node3d with box-mesh. Works fine on pc, but on android texture rect is just plain white (export including all resources in the project). I tried earlier a bit to locate the problem - I coudnt get any debug text in the text field. In SceneTexture.gd I put signal in major functions to send function name to show it in the separate text field. Worked on pc, but couldnt get anything at all on phone. There are no errors or warnings at all - but I dont have on phone any real debug system.

**Comment by ydeltastar** [comment]
Strange. I tested the demo on a real and virtual device and it works fine on mobile and compatibility mode. There isn't platform or render specific logic in the addon. It could be a project or export setting.

Try the latest version from this repository instead of the asset library. If it still happens please send me the project so I can take a look.

**Comment by so1975** [comment]
Awesome! Version 0.2 works on android too! Thanks for sharing this! :)

**Comment by ydeltastar** [comment]
Great! Thank you for reporting and testing. Closing this as completed.
